### ISSUE TITLE
Consider add a expiration time to the signature when doing bridge onchain <> offchain

### ISSUE THREAD

**Issue by nfmelendez** [wormfare/contracts#2]
Here:
https://github.com/wormfare/contracts/blob/main/contracts/TokenSale.sol#L207

In my opinion you should have an expiration field to check and to be part of the signature, like

https://github.com/nfmelendez/funflowerfarm-contracts/blob/proxyAndBank/contracts/Bank.sol#L80

see  uint deadline parameter

Regards!

**Comment by andrew-sol** [comment]
Thanks for the feedback!

Indeed, the `deadline` param is usually used in the EIP-712 signatures. In this contract, the deadline param was deliberately omitted since it does not impact the security in any way. The signature is used only to ensure the user gets the correct discount and their referral (parent) user gets their reward. Users may safely reuse the same signature multiple times.

You can review the security audit for this contract here: https://github.com/wormfare/contracts/blob/main/audits/TokenSale.pdf
